#!/bin/bash

for project in *; do
  [[ ! -d "$project" || ! -f "$project/config" || ! -f "$project/update" ]] && continue
  (
    # Sub-shell to isolate cd and config
    cd "$project"
    source "config"
    cp template "../$project.bat"
    for file in *; do
        [[ "$file" == "config" || "$file" == "template" ]] && continue
        echo "curl $source$file -o $destination$file" >>"../$project.bat"
    done
    unix2dos -q "../$project.bat"
  )
done
