#!/bin/bash

cd "$(dirname "$0")"

# Since this will run unattended, we should log everything
exec > >(awk '{print strftime("[%Y-%m-%d %H:%M:%S]"), $0}' | tee -a update.log) 2>&1

# Update the .bat files and push them
git pull
./generate
git add *.bat
git commit -m "Updated scripts"
git push origin main

# Run game specific update/restart
for project in *; do
  [[ ! -d "$project" || ! -f "$project/config" || ! -f "$project/update" ]] && continue
  ( "$project/update" )
done
