name: Update Valheim-Easy server

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >~/.ssh/id_ed25519
          cat <<EOF > ~/.ssh/config
          Host games-server
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              Port ${{ secrets.SSH_PORT }}
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              HostKeyAlgorithms +ssh-ed25519
          EOF
          chmod 0600 ~/.ssh/config ~/.ssh/id_ed25519

      - name: Run update script on server
        run: |
          ssh games-server "/srv/games/NeverPortal-Configs/update"

